services:
    web:
        build: ./app
        # command: gunicorn -k gevent -w 1 -b 0.0.0.0:5000 wsgi:app
        ports:
            - 5000:5000
        volumes:
            - ./app:/app
        depends_on:
            - redis
    worker:
        build: ./worker
        # command: rq worker -u redis://redis:6379
        depends_on:
            - redis
            - web
        deploy:
            resources:
                limits:
                    cpus: "4"
                    memory: "6GB"
            replicas: 2
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
    redis:
        image: redis:latest
    nginx:
        build: ./nginx
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./app/static:/app/static
          - ./certbot/www:/var/www/certbot
          - ./certbot/conf/live/vid-dat.com:/etc/letsencrypt
        depends_on:
          - web
          - certbot
    certbot:
      image: certbot/certbot:latest
      volumes:
        - ./certbot/www:/var/www/certbot
        - ./certbot/conf:/etc/letsencrypt
      command: certonly --webroot -w /var/www/certbot --force-renewal --email viddatconfirm@gmail.com -d vid-dat.com --agree-tos
